### ISSUE TITLE
ERROR parsing data

### ISSUE THREAD

**Issue by lcaleixo** [mancuniancol/script.quasar.eztv-mc#1] opened 2016-01-29 17:42 UTC
this error happened when I went to see episodes of the big bang theory ..
The series 01-08 .. What would that be?

**Comment by lcaleixo** [comment] 2016-01-29 17:55
Leave only enabled EZTV ... For tests ... and this error ...

**Comment by mancuniancol** [comment] 2016-01-29 18:12
Thank you for the feedback, but without your kodi log in debug mode. It is nothing that I can do. You can use pastebin.com to share.

**Comment by lcaleixo** [comment] 2016-01-29 18:27
http://pastebin.com/uMNfUPKw

**Comment by lcaleixo** [comment] 2016-01-29 18:42
Hello
I did a more complete, with many trials and errors ..
http://pastebin.com/2DYYv76w
S01-S08 ERROR parsing DATE
S09 ran ..
The big band theory
and other older series also

**Comment by lcaleixo** [comment] 2016-01-29 18:49
15:36:37 T:8060  NOTICE: [script.quasar.eztv-mc]  https://eztv.ag/search/the-big-bang-theory-s08e03
15:36:38 T:3084   DEBUG: DialogProgress::StartModal called
15:36:38 T:3084   DEBUG: ------ Window Init (DialogProgress.xml) ------
15:36:39 T:8060  NOTICE: [script.quasar.eztv-mc] Accepted Keywords: ['HDTV', '720p', '1080p']
15:36:39 T:8060  NOTICE: [script.quasar.eztv-mc] Blocked Keywords: []
15:36:39 T:8060  NOTICE: [script.quasar.eztv-mc] min Size: 0.0 GB
15:36:39 T:8060  NOTICE: [script.quasar.eztv-mc] max Size: MAX
15:36:39 T:8060   ERROR: [script.quasar.eztv-mc] >>>>>>>ERROR parsing data<<<<<<<

but if you look for the search finds 1 link
https://eztv.ag/search/the-big-bang-theory-s08e03

**Comment by mancuniancol** [comment] 2016-01-29 18:59
Please,  do not attach code here. I will check your log this weekend, I will keep you posted.

**Comment by lcaleixo** [comment] 2016-01-29 19:01
sorry.
I am new here..

**Comment by mancuniancol** [comment] 2016-01-29 20:25
Don't worry. It is not big deal ;) .

**Comment by mancuniancol** [comment] 2016-01-30 00:38
Thank you, I was able to reproduce the issue with your log. I've fixed the problem and I've released version 1.0.1.  Please, could you give your feedback from the new version? if you're still having trouble, let me know. I will do a drastic change to implement Beautifulsoup to do the parse.  It is simple, but it will add a dependency to use the provider :P

**Comment by lcaleixo** [comment] 2016-01-30 14:17
Does not work.
It stands on the screen of opening signal.
I think there has to be just one link torrent
When he finds someone with 2 links works well ...

**Comment by mancuniancol** [comment] 2016-01-30 14:27
Log?  I remind you. That it is only way, I can reproduce the problem. In my side works. Then, I need your log to see the difference.

**Comment by lcaleixo** [comment] 2016-01-30 14:28
http://pastebin.com/EspVyBLY

**Comment by lcaleixo** [comment] 2016-01-30 14:30
https://www.sendspace.com/file/bviq8n

**Comment by lcaleixo** [comment] 2016-01-30 14:32
When he finds someone with 2 links works well ...
Or more

https://www.sendspace.com/file/xau7cg

**Comment by mancuniancol** [comment] 2016-01-30 14:46
Thanks for you log, I was able to reproduce the issue. But, it is not problem from provider.
[code]
09:42:28 T:14560  NOTICE: [script.quasar.eztv-mc] >>>>>>1 torrents sent to Quasar<<<<<<<
[/code]
It seems something with the magnet itself.  It is not available or it is dead.

You can check the rest of the log information and you will see that it is quasar business.

I will close this issue because the provider version 1.0.1 is giving the information to Quasar without problem.

**Closed by mancuniancol** 2016-01-30 14:46 UTC
